sources:
  - name:
    handler:
      postgraphile:
        connectionString:
        options:
          simpleCollections: only
        appendPlugins:
          - postgraphile-plugin-connection-filter
transforms:
  - resolversComposition:
      mode: wrap
      compositions:
        - resolver: "Query.*"
          composer: ./src/composers/isAuth.js#isAuth
        - resolver: "Mutation.*"
          composer: ./src/composers/isAuth.js#isAuth
        - resolver: "Subscription.*"
          composer: ./src/composers/isAuth.js#isAuth
additionalResolvers:
additionalTypeDefs:
serve:
  browser: false
  playgroundTitle: Nexus
