sources:
  - name:
    handler:
      postgraphile:
        connectionString:
        options:
          simpleCollections: only
transforms:
  - resolversComposition:
      mode: wrap
      compositions:
        - resolver: "Query.*"
          composer: ./src/isAuth.js#isAuth
